### ISSUE TITLE
svn: E170001: Authentication error from server: Internal server error in authentication

### ISSUE THREAD

**Issue by defcon8** [MarkusH1975/svnserver.svn.mh#3]
Hi,

First of all great project, I tried to migrate my old (dsm 6.x) based SVN data directory to your system.. using the instructions. That all was straight forward. Except when I try to checkout the repository I get this error:

```
svn co svn://192.168.0.111/lumina
svn: E170013: Unable to connect to a repository at URL 'svn://192.168.0.111/lumina'
svn: E170001: Authentication error from server: Internal server error in authentication
```

So my SVN repo is in place.. my directory structure looks like:
/volume1/svn/svnserver.svn.mh/volume/svnrepo/lumina

I cannot get it work.. any suggestions?

**Comment by MarkusH1975** [comment]
check user/password in file conf/passwd

https://github.com/MarkusH1975/svnserver.svn.mh#svn-access-control

**Comment by MarkusH1975** [comment]
Closed

**Comment by MarkusH1975** [comment]
See updated ACL:
https://github.com/MarkusH1975/svnserver.svn.mh#svn-access-control
