### ISSUE TITLE
Allow repositories to reside outside the docker container

### ISSUE THREAD

**Issue by Huseriato** [MarkusH1975/svnserver.svn.mh#4]
The doku tells I should "backup" the svn repositories to a location inside the docker container. But I want to serve them as file:\\nas\svn in my local network, too. Also I don't like the idea of putting productive data inside a docker container. Is it possible to tell the docker container the desired location of the repository files?

**Comment by MarkusH1975** [comment]
See documentation:
https://github.com/MarkusH1975/svnserver.svn.mh#volumes
The data is not stored in the docker container.

**Comment by Huseriato** [comment]
Can you please explain or clarify "[Create a Backup! Copy your existing SVN-Repositories into the folder](https://github.com/MarkusH1975/svnserver.svn.mh#svn-copy-existing-repository)"? That is the point I'm struggeling about. Why not leave the respoistories in /volume1/svn and use the /volume1/docker directory for the docker container. I don't understand, why there is a seperate backup needed. Thanks in advance.

**Comment by MarkusH1975** [comment]
It is always good to have a backup.

**Comment by Huseriato** [comment]
But the "backup" becomes the live repository and the old repository is the backup after this. Also users that are using the file:// protocol to point to their repostitories are using the "backup" (e.g. previous live repository) and via the new created server the copy is accessed.

So isn't it correct to change the documentation: "Move your current repository to location xyz". Also "It's aso recommended to create a backup before installing the docker container" or something like this.
