### ISSUE TITLE
How to uninstall completely?

### ISSUE THREAD

**Issue by ytbewhitebox** [MarkusH1975/svnserver.svn.mh#6]
First of all thanks for the great work.

I have a request:
Would you kindly mind to elaborate how to completely uninstall everything that was automatically installed with your SVN Server?
I would like to restore files as they were before installing.

Thanks for your help.

Kind Regards!

**Comment by MarkusH1975** [comment]
Hi,
Just stop the docker container and remove the folder.

**Comment by ytbewhitebox** [comment]
Okay! Thanks. What about the monitorix and tini, etc. installation?

**Comment by MarkusH1975** [comment]
This all inside the docker

**Comment by ytbewhitebox** [comment]
/svn/svnserver.svn.mh/ or just the svnserver.svn.mh/ ?
